server:
  port: 2100

# spring.cloud.config.server.bootstrap=tru

spring:
  application:
    name: cloud-config-server2100
  cloud:
    config:
      label: master
      name: conf
      profile: _dev
      uri: http://localhost:2000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka

